services:
  todo-backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://todo-mongo:27017/todoapp
    depends_on:
      - todo-mongo
    networks:
      - backend
  todo-frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - todo-backend
    networks:
      - frontend
      - backend
  todo-mongo:
    image: mongo
    restart: always

    networks:
      - backend
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - todo-frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/backend.conf:/etc/nginx/conf.d/backend.conf
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
